# Generated by Django 5.2 on 2025-04-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='invitees',
            field=models.TextField(blank=True, default=''),
        ),
    ]
