# Generated by Django 5.2 on 2025-04-22 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_invitees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='invitees',
        ),
        migrations.AddField(
            model_name='task',
            name='invitees',
            field=models.ManyToManyField(blank=True, related_name='shared_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
