# Generated by Django 5.2 on 2025-04-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
    ]
