# Generated by Django 5.2 on 2025-04-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_completed'),
        ('myapp', '0005_rename_type_task_description_remove_task_duration'),
    ]

    operations = [
    ]
